# 46.1 제네레이터란?

ES6에 도입된 제네레이터는 코드 블록의 실행을 일시 중지했다가 필요한 시점에 재개할 수 있는 특수한 함수다. 제네레이터와 일반 함수의 차이는 다음과 같다

### 1. 제너레이터 함수는 함수 호출자에게 함수 실행의 제어권을 양도할 수 있다.

일반함수는 제어권이 함수에게 넘어가는 반면, 제네레이터 함수는 함수 실행을 함수 호출자가 제어할 수 있따. 즉 함수 호출자가 함수 실행을 일시중지하거나 재개할 수 있다. 이는 함수의 제어권을 함수가 독점하는 것이 아니라 함수 호출자에게 양도할 수 있다는 것을 의밓나다.

### 2. 제네레이터 함수는 함수 호출자와 함수의 상태를 주고받을 수 있다.

일반함수를 호출하면 매개변수로 외부에서 값을 주입받고, 함수가 실행되고 있는 동안에는 함수 외부에서 내부로 값을 전달할 수 없는 반면, 제너레이터 함수는 함수 호출자와 양방향으로 함수의 상태를 주고 받을 수 있다. 즉, 제너레이터 함수는 함수 호출자에게 상태를 전달할 수 있꼬 함수 호출자로부터 상태를 전달받을 수도 있다.

### 3. 제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.

일반함수를 호출하면 함수코드를 실행 후 결과값을 반환한다. 제너레이터 함수를 호출하면 함수 코드를 실행하는것이 아니라 이터러블 이면서 동시에 이터레이터인 제너레이터 객체를 반환한다.

# 46.2 제너레이터 함수 정의

제너레이터 함수는 `function*` 키워드로 선언하고 하나 이상의 yield 표현식을 포함한다. 이것을 제외하면 일반 함수와 동일하다.

애스터 리스크(\*)의 위치는 function 키워드와 함수 사이에 위치하면 되며 띄어쓰기는 무관하다. 단, 일관성 유지를 위해 function키워드 바로 뒤에 붙이는 것이 권장된다.  
또한,제너레이터 함수는 화살표 함수로 정의할 수 없으며,  
제너레이터 함수는 new 연산자와 함께 생성자 함수로 호출할 수 없다.

# 46.3 제너레이터 함수 정의

제너레이터 함수를 호출하면 일반함수처럼 코드블록을 실행하는것이 아니라 제너레이터 객체를 생성해 반환한다. 제너레이터 함수가 반환한 제너레이터 객체는 이터러블이면서 이터레이터이다.  
제너레이터 객체는 Symbol.iterator 메서드를 상속받는 이터러블이면서, value.done 프로퍼티를 갖는 이터레이터 리절트 객체를 반환하는 next메서드를 소유한 이터레이터이다.
제너레이터 객체는 그자체로 이터레이터이므로 별도의 메서드 호출을 통한 이터레이터 생성 과정이 불필요하다.

```js
function* genFunc() {
  yield 1;
  yield 2;
}
//제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.
const generator = genFunc();

//제너레이터 객체에는 Symbol.iterator메서드가 있다.
console.log(Symbol.iterator in generator); //tre
//제너레이터 객체에는 next메서드가 있다.
console.log("next" in generator); //tre
```

제너레이터 객체는 next메서드를 갖는 이터레이터이지만, 이터레이터에는 없는 return, throw 메서드를 갖는다.  
제너레이터 객체의 세개의 메서드를 호출하면 다음과 같이 동작한다

- next 메서드: 제너레이터 함수의 yield 표현식까지 코드블록을 실행하고 yield된 값을 value 프로퍼티 값으로, done 프로퍼티의 값을 false로 갖는 이터레이터 리절트 객체를 반환한다.
- return 메서드: 인수로 전달받은 값을 value 프로퍼티 값으로, done 프로퍼티의 값으로 true를 갖는 이터레이터 리절트 객체를 반환한다.
- throw 메서드 : 인수로 전달받은 에러를 발생시키고 undefined를 value 프로퍼티 값으로, done 프로퍼티의 값으로 true를 갖는 이터레이터 리절트 객체를 반환한다.

```js
function* genFunc() {
  try {
    yield 1;
    yield 2;
  } catch (error) {
    console.log(error);
  }
}
//제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.
const generator = genFunc();
console.log(generator.next()); //{value : 1, done: false}
console.log(generator.return("end")); //{value : end, done: true}

//error case
console.log(generator.throw("Error!")); //{value : undefined, done: false}
```

# 46.4 제너레이터 일시 중지와 재개

제너레이터는 yield 키워드와 next메서드를 통해 실행을 일시 중지했다가 필요한 시점에 다시 재개할 수 있다. 일반 함수는 호출 이후 제어권을 독점하지만 제너레이터는 함수 호출자에게 제어권을 양도하여 필요한 시점에 함수 실행을 재개할 수 있다.
제너레이터 함수를 호출하면 제너레이터 함수 코드 블록이 실행되는 것이 아니라 제너레이터 객체를 반환한다고 하였다.
이터레이터인 제너레이터 객체에는 next메서드가 있으며 객체의 next메서드를 호출하면 제너레이터 함수의 코드 블록을 실행한다.

```js
function* genFunc() {
  try {
    yield 1;
    yield 2;
  } catch (error) {
    console.log(error);
  }
}
//제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.
const generator = genFunc();

//처음 next 메서드를 호출하면 첫번재 yield 표현식까지 실행되고 중지된다.
//next메서드는 이터레이터 리절트 객체를 반환한다.
// value에는 yield 표현식에서 yield된 값 1이 할당되며
// done에는 제너레이터 함수가 끝까지 실행되었는지를 판단하는 false가 할당된다.
console.log(generator.next());

// value에는 yield 표현식에서 yield된 값 2이 할당되며
// done에는 제너레이터 함수가 끝까지 실행되었는지를 판단하는 false가 할당된다.
console.log(generator.next());

// value에는 함수의 반환값 undfined가 할당된다.
// done에는 제너레이터 함수가 끝까지 실행되었는지를 판단하는 true가  할당된다.
console.log(generator.next());
```

제너레이터 객체이 next메서드를 호출하면 yield 표현식까지 실행되고 일시중지 되며 함수의 제어권이 호출자로 양도된다.
이후 필요한 시점에 호출자가 다시 next메서드를 호출하면 일시중지된 코드부터 실행을 재개하며 다음 yield 표현식까지 실행되고 또 다시 일시 중지된다.
이때 제너레이터 객체의 next 메서드는 value, done 프로퍼티를 갖는 이터레이터 리절트 객체를 반환하다. 해당 리절트 객체의 value프로퍼티에는 yield 표현식에서 yield된 값이 할당되고  
done 프로퍼티에는 제너레이터 함수가 현재 끝까지 실행되었는지를 나타내는 불리언 값이 할당된다.

next메서드를 반복호출하여 yield 표현식까지 실행하는 과정과 일시중지하는 과정을 반복하다가 제너레이터 함수가 끝까지 실행되면, 이터레이터 리절트 객체의 value프로퍼티에는 제너레이터 함수의 반환값이 할당되고
done 프로퍼티에는 제너레이터 함수가 끝까지 실행되었음을 나타내는 true가 할당된다.

단, 이터레이터의 next메서드와 달리 제너레이터 객체의 next메서드에는 인수를 전달할 수 있다.  
제너레이터 객체의 next메서드에 전달한 인수는 제너레이터 함수의 yield 표현식을 할당받는 변수에 할당된다.

```js
function* genFunc() {
  // 처음 next 메서드를 호출하면 첫 번째 yield 표현식까지 실행되고 일시 중지된다.
  // 이때 yield된 값 1은 next 메서드가 반환한 이터레이터 리절트 객체의 value 프로퍼티에 할당된다.
  // x 변수에는 아직 아무것도 할당되지 않았다. x 변수의 값은 next 메서드가 두 번째 호출될 때 결정된다.
  const x = yield 1;

  // 두 번째 next 메서드를 호출할 때 전달한 인수 10은 첫 번째 yield 표현식을 할당받는 x 변수에 할당된다.
  // 즉, const x = yield 1;은 두 번째 next 메서드를 호출했을 때 완료된다.
  // 두 번째 next 메서드를 호출하면 두 번째 yield 표현식까지 실행되고 일시 중지된다.
  // 이때 yield된 값 x + 10은 next 메서드가 반환한 이터레이터 리절트 객체의 value 프로퍼티에 할당된다.
  const y = yield x + 9;

  // 세 번째 next 메서드를 호출할 때 전달한 인수 20은 두 번째 yield 표현식을 할당받는 y 변수에 할당된다.
  // 즉, const y = yield (x + 10);는 세 번째 next 메서드를 호출했을 때 완료된다.
  // 세 번째 next 메서드를 호출하면 함수 끝까지 실행된다.
  // 이때 제너레이터 함수의 반환값 x + y는 next 메서드가 반환한 이터레이터 리절트 객체의 value 프로퍼티에 할당된다.
  // 일반적으로 제너레이터의 반환값은 의미가 없다.
  // 따라서 제너레이터에서는 값을 반환할 필요가 없고 return은 종료의 의미로만 사용해야 한다.
  return x + y;
}

const generator = genFunc(0);

// 처음 호출하는 next 메서드에는 인수를 전달하지 않는다.
// 만약 처음 호출하는 next 메서드에 인수를 전달하면 무시된다.
// next 메서드가 반환한 이터레이터 리절트 객체의 value 프로퍼티에는 첫 번째 yield된 값 1이 할당된다.
let res = generator.next();
console.log(res); // {value: 1, done: false}

// next 메서드에 인수로 전달한 10은 genFunc 함수의 x 변수에 할당된다.
// next 메서드가 반환한 이터레이터 리절트 객체의 value 프로퍼티에는 두 번째 yield된 값 20이 할당된다.
res = generator.next(10);
console.log(res); // {value: 20, done: false}

// next 메서드에 인수로 전달한 20은 genFunc 함수의 y 변수에 할당된다.
// next 메서드가 반환한 이터레이터 리절트 객체의 value 프로퍼티에는 제너레이터 함수의 반환값 30이 할당된다.
res = generator.next(20);
console.log(res); // {value: 30, done: true}
```

이처럼 제너레이터 함수는 next메서드와 yield 표현식을 통해 함수 호출자와 함수 상태를 주고받을 수 있다.  
함수 호출자는 next메서드를통해 yield 표현식까지 함수를 실행시켜 제너레이터 객체가 관리하는 상태(yield된 값)을 가져올 수 있고 next메서드에 인수를 전달하여 제너레이터 객체에 상태를 밀어넣을 수 있다.  
이러한 제너레이터의 특성을 활용하면 비동기 처리를 동기처럼 구현할 수 있다.

# 46.5 제너레이터의 활용

## 46.5.1 이터러블 구현.

제러네이터 함수를 사용하면 이터레이션 프로토콜을 준수해 어터러블을 생성하는 방식보다 간단히 이터러블을 구현할 수 있다.  
이터레이션 프로토콜을 준수하여 무한 피보나치 수열을 생성하는 함수를 구현한다면, 다음과 같다.

```js
const infiniteFibonacci = (function () {
  let [pre, cur] = [0, 1];

  return {
    [Symbol.iterator]() {
      return this;
    },
    next() {
      [pre, cur] = [cur, pre + cur];
      // 무한 이터러블이므로 done 프로퍼티를 생략한다.
      return { value: cur };
    },
  };
})();

// infiniteFibonacci는 무한 이터러블이다.
for (const num of infiniteFibonacci) {
  if (num > 10000) break;
  console.log(num); // 1 2 3 5 8...2584 4181 6765
}
```

제너레이터를 사용한다면 조금 더 쉽게 이터러블을 구현할 수 있다.

```js
// 무한 이터러블을 생성하는 제너레이터 함수
const infiniteFibonacci = (function* () {
  let [pre, cur] = [0, 1];

  while (true) {
    [pre, cur] = [cur, pre + cur];
    yield cur;
  }
})();

// infiniteFibonacci는 무한 이터러블이다.
for (const num of infiniteFibonacci) {
  if (num > 10000) break;
  console.log(num); // 1 2 3 5 8...2584 4181 6765
}
```

## 46.5.2 비동기 처리

제너레이터 함수는 next메서드와 yield표현식을 통해 함수 호출자와 함수 상태를 주고받을 수 있다. 이러한 특성을 활용하면 프로미스를 사용한 비동기 처리를 동기처리 처럼 구현할 수 있다.
프로미스의 후속처리 메서드 `then`/`catch`/`finally` 없이 비동기 처리 결과를 반환하도록 구현할 수 있다.

# 46.6 async/awiat

제너레이터를 사용해서 비동기처리를 동기처럼 동작하도록 구현했지만 코드가 길고 가독성이 떨어진다.  
ES8에는 제너레이터보다 간단하고 가독성 좋게 비동기 처리를 동기 처리처럼 동작하도록 구현할 수 있는 async/awiat 가 도입되었다.
async/awiat 는 ㅍ로미스를 기반으로 동작하며 async/awiat를 사용하면 프로미스의 후속 처리 메서드에 콜백함수를 전달해서 비동기 처리 결과를 처리할 필요없이, 마치 동기 처리처럼 프로미스를 사용ㅎㄹ 수 있다.

## 46.6.1 async 함수

await 키워드는 반드시 async 함수 내부에서 사용해야한다. async함수는 async키워드를 사용해 정의하며 언제나 프로미스를 반환한다.  
async함수가 명시적으로 프로미스를 반환하지 않더라도 async함수는 암묵적으로 반환값을 resolve하는 프로미스를 반환한다.

```js
// async 함수 선언문
async function foo(n) {
  return n;
}
foo(1).then((v) => console.log(v)); // 1

// async 함수 표현식
const bar = async function (n) {
  return n;
};
bar(2).then((v) => console.log(v)); // 2

// async 화살표 함수
const baz = async (n) => n;
baz(3).then((v) => console.log(v)); // 3

// async 메서드
const obj = {
  async foo(n) {
    return n;
  },
};
obj.foo(4).then((v) => console.log(v)); // 4

// async 클래스 메서드
class MyClass {
  async bar(n) {
    return n;
  }
}
const myClass = new MyClass();
myClass.bar(5).then((v) => console.log(v)); // 5
```

단, 클래스의 constructor메서드는 async 메서드가 될 수 없다. 클래스의 constructor메서드는 인스턴스를 반환해야하지만, async 함수는 언제나 프로미스를 반환해야하기 때문이다.

```js
class MyClass {
  async constructor() { }
  // SyntaxError: Class constructor may not be an async method
}

const myClass = new MyClass();
```

## 46.6.2 await 키워드

await 키워드는 프로미스가 settled 상태가 될때까지 대기하다가 settled 상태가 되면 프로미스가 resolve한 결과를 반환한다. await는 반드시 프로미스 앞에서 사용해야한다.
단, 모든 프로미스에 await를 사용하는 것은 주의해야한다. 모든 비동기 처리를 순차적으로 처리할 경우 긴 시간이 소요된다. 만약 개별적으로 진행되는 여러개의 비동기처리를 수행할 경우 Promise.all등을 사용하는것이 좋다.

```js
async function foo() {
  const a = await new Promise((resolve) => setTimeout(() => resolve(1), 3000));
  const b = await new Promise((resolve) => setTimeout(() => resolve(2), 2000));
  const c = await new Promise((resolve) => setTimeout(() => resolve(3), 1000));

  console.log([a, b, c]); // [1, 2, 3]
}

foo(); // 약 6초 소요된다.

async function fooWithPromiseAll() {
  const res = await Promise.all([
    new Promise((resolve) => setTimeout(() => resolve(1), 3000)),
    new Promise((resolve) => setTimeout(() => resolve(2), 2000)),
    new Promise((resolve) => setTimeout(() => resolve(3), 1000)),
  ]);

  console.log(res); // [1, 2, 3]
}

fooWithPromiseAll(); // 약 3초 소요된다.
```

단, 순차적인 처리 순서가 보장되어야 한다면 모든 프로미스에 await 키워드를 써서 순차적으로 처리할 수 밖에 없다.

```js
async function bar(n) {
  const a = await new Promise((resolve) => setTimeout(() => resolve(n), 3000));
  // 두 번째 비동기 처리를 수행하려면 첫 번째 비동기 처리 결과가 필요하다.
  const b = await new Promise((resolve) => setTimeout(() => resolve(a + 1), 2000));
  // 세 번째 비동기 처리를 수행하려면 두 번째 비동기 처리 결과가 필요하다.
  const c = await new Promise((resolve) => setTimeout(() => resolve(b + 1), 1000));

  console.log([a, b, c]); // [1, 2, 3]
}

bar(1); // 약 6초 소요된다.
```

## 46.6.3 에러 처리

비동기 처리를 위한 콜백 패턴의 단점 중 하나는 에러처리가 어렵다는 것이다. 에러는 호출자 방향으로 전파되며 즉 콜스택 아래 방향(실행중인 실행 컨텍스트가 푸시되기 직전 푸시된 실행컨텍스트 방향)으로 전파된다.
그러나 비동기 함수의 콜백함수를 호출한 것은 비동기 함수가 아니기때문에 try...catch문을 사용할 수 없다.

```js
try {
  setTimeout(() => {
    throw new Error("Error!");
  }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다
  console.error("캐치한 에러", e);
}
```

반면 asyc/await에서 에러처리는 try...catch문을 사용할 수 있다.  
콜백함수를 인수로 전달받는 비동기 함수와는 달리 프로미스를 반환하는 비동기 함수는 명시적으로 호출할 수 있기 때문에 호출자가 명확하다.

```js
const fetch = require("node-fetch");

const foo = async () => {
  try {
    const wrongUrl = "https://wrong.url";

    const response = await fetch(wrongUrl);
    const data = await response.json();
    console.log(data);
  } catch (err) {
    console.error(err); // TypeError: Failed to fetch
  }
};

foo();
```

혹은 async 메서드 내부에서 catch문을 사용하지 않고 Promise의 후속처리 메서드를 사용할 수 있다.
async 메서드 내부에서 오류가 발생하고 따로 에러처리를 하지 않는다면 async 메서든는 에러를 reject하는 프로미스를 반환하기 때문이다.

```js
const fetch = require("node-fetch");

const foo = async () => {
  const wrongUrl = "https://wrong.url";

  const response = await fetch(wrongUrl);
  const data = await response.json();
  return data;
};

foo().then(console.log).catch(console.error); // TypeError: Failed to fetch
```
